const mongoose = require("mongoose");
const userSchema = new mongoose.Schema(
    {
        name:{
            type:String,
            required:true,
            trim:true,
            minlength:2,
            maxlength:80
        },
        email:{
            type:String,
            required:true,
            unique:true,
            lowercase:true,
            trim:true,
            maxlength:254
        },
        password:{
            type:String,
            required:true,
            minlength:8
        },
        passwordResetToken:{
            type:String,
            select:false
        },
        passwordResetExpires:{
            type:Date,
            select:false
        },
        passwordResetRequestedAt:{
            type:Date,
            select:false
        },
        passwordChangedAt:{
            type:Date,
            select:false
        },
        authVersion:{
            type:Number,
            default:0,
            select:false
        },
        role:{
            type:String,
            enum:["user","admin"],
            default:"user"
        }
    },
    {
        timestamps:true
    }
);
module.exports = mongoose.models.User || mongoose.model("User", userSchema);
